nginx:
  build: docker/nginx
  ports:
    - "443:443"
  links:
    - "go"
  restart: always

go:
  build: docker/go
  links:
    - "mongodb"
  restart: always

mongodb:
  build: docker/mongo
  container_name: user_db
  restart: always
